import Head from 'next/head';
import Form from '../components/Form';
import Header from '../components/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Form />
    </div>
  );
}
