import Head from 'next/head';
import Footer from '../components/Footer';
import Form from '../components/Form';
import Header from '../components/Header';

export default function Home() {
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Form />
      <Footer />
    </div>
  );
}
